### ISSUE TITLE
Syft hangs when run in CircleCI

### ISSUE THREAD

**Issue by tri-adam** [anchore/syft#1439]
**Please provide a set of steps on how to reproduce the issue**

Run Syft in a CircleCI pipeline without the quiet (`-q`) or verbose (`-v`) flags. Specifically, the job I'm running is:

```
  generate_sbom:
    docker:
      - image: alpine:3.17
    steps:
      - attach_workspace:
          at: /docker
      - run:
          name: Install Syft
          command: wget -q -O - https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Generate SBOM
          command: syft packages -o cyclonedx-json=/docker/sbom.cdx.json "docker-archive:/docker/service.tar"
      - persist_to_workspace:
          root: /docker
          paths:
            - sbom.cdx.json
```

Eventually, the `Generate SBOM` step times out with:

```
Too long with no output (exceeded 10m0s): context deadline exceeded
```

If I add the quiet (`-q`) or verbose (`-v`) flags, the command completes in a few seconds.

**What happened**:

`syft packages` hangs when run in a CircleCI environment unless the quiet (`-q`) or verbose (`-v`) flags are added.

**What you expected to happen**:

Syft should complete regardless of whether the quiet/verbose flags are present.

**Anything else we need to know?**:

I suspect this may have the same root cause as https://github.com/anchore/grype/issues/1051.

**Environment**:
- Output of `syft version`:
```
Application:        syft
Version:            0.65.0
JsonSchemaVersion:  6.0.0
BuildDate:          2023-01-04T17:00:24Z
GitCommit:          bc1edb9c8a2fb4824bfdcac6147edc2bbf47aaf6
GitDescription:     v0.65.0
Platform:           linux/amd64
GoVersion:          go1.18.9
Compiler:           gc
```
- OS (e.g: `cat /etc/os-release` or similar):
```
# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.17.0
PRETTY_NAME="Alpine Linux v3.17"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

**Comment by kzantow** [comment]
Thanks, @tri-adam! It sounds like there is a simple workaround, so this isn't a critical issue for you, correct?

**Comment by tri-adam** [comment]
Yes, that's correct. The silent/verbose flags are both effective workarounds.

**Comment by StevenRoodhorst** [comment]
I would love to see this fixed as it took me quite some time to figure out what the problem was. The workaround is effective though!

**Comment by tgerla** [comment]
Developer notes for @anchore/tools: this test should probably be boolean or, not and: https://github.com/anchore/syft/blob/7de7a7990a0d7315bac2d02f5eb6f7989fd6ef2f/internal/ui/select.go#L21

**Comment by spiffcs** [comment]
@tri-adam we're thinking about this one - does the above look like the correct solution or wheelhouse? Are you still having this problem?

**Comment by willmurphyscode** [comment]
I tried implementing the solution suggested by @tgerla, but that can make it seem like `syft` isn't working. In other words, if the progress bars and spinners aren't printed, something like `syft some-large:image | grep some-package` seem to hang, because nothing will print until syft is done loading and parsing the image.

I also discovered that using 2 syft invocations without `-q` in the same shell can hang forever, which might be the same problem as is observed in CircleCI:

```
# hangs forever:
❯ cat <(syft alpine:latest | head -n 1) <(syft alpine:latest | grep binary)
^C
# runs normally:
❯ cat <(syft -q alpine:latest | head -n 1) <(syft -q alpine:latest | grep binary)
NAME                    VERSION      TYPE
busybox                 1.36.1       binary
```

**Comment by wagoodman** [comment]
Regarding `cat <(syft -q alpine:latest | head -n 1) `, I only see this hanging behavior on a mac and not linux

**Comment by wagoodman** [comment]
We haven't been able to reproduce this, the latest attempt at both latest and a v0.85.0 (closer to when this issue was opened) both seem to work just fine in circle:

```
#.circleci/config.yml
version: 2.1

jobs:
  run:
    docker:
      - image: alpine:3.17

    steps:

      - attach_workspace:
          at: /docker

      - run:
          name: Install Syft
          command: wget -q -O - https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin v0.85.0

      - run:
          name: Generate SBOM
          command: syft packages -o cyclonedx-json=/docker/sbom.cdx.json "registry:alpine:latest"

      - persist_to_workspace:
          root: /docker
          paths:
            - sbom.cdx.json

workflows:

  build_and_test:
    jobs:
      - run

```

With v0.85.0:
<img width="1010" alt="Screenshot 2024-02-09 at 4 50 17 PM" src="https://github.com/anchore/syft/assets/590471/22e96edf-adc1-4e8a-aaad-026c5bca518a">

With latest v0.104.0
<img width="1006" alt="Screenshot 2024-02-09 at 4 50 29 PM" src="https://github.com/anchore/syft/assets/590471/f25ccacb-05c1-4ca1-a80a-b54c14665987">

Since we can't reproduce this I'm going to close however, if there is ever new information please to help reproduce feel free to comment here and we can re-open the issue.
