### ISSUE TITLE
Scan with javascript-lock cataloger does not provide licenses

### ISSUE THREAD

**Issue by aslansky** [anchore/syft#1910]
When scanning with  javascript-lock cataloger the license field in the resulting bom is empty. Is there a way to get the licenses with this cataloger?

**Comment by tgerla** [comment]
Hi @aslansky, thanks for filing this issue. Do you mind attaching a lockfile or container image that you're using so we can test it out on our end? Thanks!

**Comment by aslansky** [comment]
Sure, we are using yarn.

[yarn.lock.txt](https://github.com/anchore/syft/files/11977111/yarn.lock.txt)

syft version is 0.84.1

.syft.yaml looks like this:

```
output: cyclonedx-json
file: dist/bom.json
exclude:
  - ./dist/**
  - ./node_modules/**
  - ./tmp/**
  - ./tools/**
  - ./coverage/**
  - ./.storybook/**
  - ./.nx/**
catalogers:
  - javascript-lock
  - go-mod-file
  - dotnet-deps
golang:
  search-local-mod-cache-licenses: true
  search-remote-licenses: true
```
