### ISSUE TITLE
Add licenses for Go packages

### ISSUE THREAD

**Issue by sorokinmax** [anchore/syft#1933]
**What would you like to be added**:
The filled in "licenses" field in the SBOM report for Go packages.

**Why is this needed**:
Now it looks like a disadvantage compared to other dependencies. 
Tracking license purity is an important part of software development.

**Additional context**:
License information is easy to get at https://pkg.go.dev
For example:
![image](https://github.com/anchore/syft/assets/19753153/5741f269-6476-4009-90cb-a251e71b2e09)

**Comment by kzantow** [comment]
@sorokinmax license information is not present in the `go.mod/go.sum` files or in the binary go mod data, so it needs to get retrieved from other sources. Syft already has the ability to do this for Go packages, but it is not enabled by default. There are a few places Syft can attempt to find licenses: the local go mod cache, the configured go proxy, and finally a git repo matching the Go mod. As noted in the config file documentation:
```
golang:
   # search for go package licences in the GOPATH of the system running Syft, note that this is outside the
   # container filesystem and potentially outside the root of a local directory scan
   # SYFT_GOLANG_SEARCH_LOCAL_MOD_CACHE_LICENSES env var
   search-local-mod-cache-licenses: false
   
   # specify an explicit go mod cache directory, if unset this defaults to $GOPATH/pkg/mod or $HOME/go/pkg/mod
   # SYFT_GOLANG_LOCAL_MOD_CACHE_DIR env var
   local-mod-cache-dir: ""

   # search for go package licences by retrieving the package from a network proxy
   # SYFT_GOLANG_SEARCH_REMOTE_LICENSES env var
   search-remote-licenses: false

   # remote proxy to use when retrieving go packages from the network,
   # if unset this defaults to $GOPROXY followed by https://proxy.golang.org
   # SYFT_GOLANG_PROXY env var
   proxy: ""

   # specifies packages which should not be fetched by proxy
   # if unset this defaults to $GONOPROXY
   # SYFT_GOLANG_NOPROXY env var
   no-proxy: ""
```

e.g. to enable searching both the local go mod cache and remotes, you can enable this by executing Syft like: 
```
SYFT_GOLANG_SEARCH_LOCAL_MOD_CACHE_LICENSES=true SYFT_GOLANG_SEARCH_REMOTE_LICENSES=true syft <source>
```

Does this work for you?
