### ISSUE TITLE
Control scan scope by mime types

### ISSUE THREAD

**Issue by bzemms** [anchore/syft#2057]
**What would you like to be added**:

This request is about adding this additional configuration to power user mode
```yaml
  # Scan only files with these mime types
  mimeTypes:
    - image/
    - application/
    - ....
```
**Why is this needed**:
To reduce the time / CPU / memory of scanning we want to scan only interesting files, and we want to control that by mime-type.

**Additional context**:
This is where we need it
https://github.com/anchore/syft?tab=readme-ov-file#configuration
e.g for **file-contents**
```yaml
# Cataloging file contents is exposed through the power-user subcommand
file-contents:
  cataloger:
    # enable/disable cataloging of secrets
    # SYFT_FILE_CONTENTS_CATALOGER_ENABLED env var
    enabled: true

    # the search space to look for secrets (options: all-layers, squashed)
    # SYFT_FILE_CONTENTS_CATALOGER_SCOPE env var
    scope: "squashed"

  # skip searching a file entirely if it is above the given size (default = 1MB; unit = bytes)
  # SYFT_FILE_CONTENTS_SKIP_FILES_ABOVE_SIZE env var
  skip-files-above-size: 1048576

  # file globs for the cataloger to match on
  # SYFT_FILE_CONTENTS_GLOBS env var
  globs: []
```
