### ISSUE TITLE
disabling catalogers is not working in power user

### ISSUE THREAD

**Issue by tomerse-sg** [anchore/syft#2074]
**What happened**:
i'm trying to disable a power-user cataloger using the .syft.yaml and it ignores it.
I think it is always puts "true" and don't take the value from the configuration.
```
		app.Secrets.Cataloger.Enabled = true
		app.FileMetadata.Cataloger.Enabled = true
		app.FileContents.Cataloger.Enabled = true
		app.FileClassification.Cataloger.Enabled = true
		tasks, err := eventloop.Tasks(app)
		if err != nil {
			errs <- err
			return
		}
```
**What you expected to happen**:
take the value from the configuration.
**Steps to reproduce the issue**:
for example, update this line in the yaml:
```
file-metadata:
  cataloger:
    # enable/disable cataloging of file metadata
    # SYFT_FILE_METADATA_CATALOGER_ENABLED env var
    enabled: false
```

and run syft power-user
**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: latest
- OS (e.g: `cat /etc/os-release` or similar): macOS
