### ISSUE TITLE
Problems with version 0.101.0 and configuration digests

### ISSUE THREAD

**Issue by JorgoSLK** [anchore/syft#2511]
**What happened**:
1.
With Version V.0.101.0 i used my own .syft.yml Configuration and i get this Error:
```
invalid application config: the config file option 'exclude-binary-overlap-by-ownership' has been removed, please use 'relationships.exclude-binary-packages-with-file-ownership-overlap' instead
```

I renamed it and it's OK

Please Update your Documentation.

2.
I get this Error:
```
invalid application config: invalid file metadata selection: "owned-files"
```

I remove the Property and it works again!

```
file:

   metadata: 
      # select which files should be captured by the file-metadata cataloger and included in the SBOM. 
      # Options include:
      #  - "all-files": capture all files from the search space
      #  - "owned-files": capture only files owned by packages
      #  - "unowned-files": capture only files not owned by packages
      #  - "no-files", "": do not capture any files
      # SYFT_FILE_METADATA_SELECTION env var
      **# selection: "owned-files"**
```

3.
I run this cmd-line under windows:
```
syft file:C:\Users\Public\Projects\workplace\...\target\Example.war -o cyclonedx-xml >SBOM-Cyclonedx.xml
```
In the Result i get only <hash alg="**SHA-1**"></hash>

Configuration:
```
file:
   metadata: 
      # the file digest algorithms to use when cataloging files (options: "md5", "sha1", "sha224", "sha256", "sha384", "sha512")
      # SYFT_FILE_METADATA_DIGESTS env var
      **digests: ["sha256"]**

source:
  # options affecting the file source type
  file:
    # the file digest algorithms to use on the scanned file (options: "md5", "sha1", "sha224", "sha256", "sha384", "sha512")
    **digests: ["sha256"]**
```
I can choose whatever i want and get only SHA-1

with this tool for example i get all the formats: "md5", "sha1", "sha224", "sha256", "sha384", "sha512"
call mvn clean install **org.cyclonedx:cyclonedx-maven-plugin:2.7.2:makeAggregateBom** -DskipTests=true

Is this Option not Working or what make i wrong

**Comment by wagoodman** [comment]
I have updates inbound for 1 & 2, however, I cannot reproduce 3:

```
file:
   metadata: 
      digests: ["sha256", "sha1", "md5"]

source:
  # options affecting the file source type
  file:
    digests: ["sha256", "sha512"]

```

```
$ go run ./cmd/syft -q alpine:latest -o json | jq '.files[].digests[].algorithm' | sort | uniq

"md5"
"sha1"
"sha256"
```

```
$ go run ./cmd/syft -q go.mod -o json | jq '.source.metadata.digests[].algorithm' | sort | uniq
"sha256"
"sha512"
```

I'm running this from a mac, but I don't see how that could come into play -- can you verify that you are seeing `file.metadata.digests` and `source.file.digests` not responding to input?
