### ISSUE TITLE
Golang: Search remote licenses not working in a CI pipeline when scanning Docker image

### ISSUE THREAD

**Issue by Joerki** [anchore/syft#2798]
**What happened**:
In our CI pipeline we run syft to scan a Docker image. No Go environment is present. search-remote-licenses (in env or .syft.yaml) is configured as "true". 

But Syft does not write license information into Syft-JSON file.

It is working on my local machine where I have a Go installation.

It looks that search remote licenses function has a path dependency that it should not have when working in an environment without Go.
 
**What you expected to happen**:
If search-remote-licenses is set by config file or environment file it should work always if set.

**Steps to reproduce the issue**:
On a machine with Go installation ($HOME/go exists):

```
(base) joerg@delly:~/project$ cat ~/.syft.yaml 

quiet: false

check-for-app-update: false

parallelism: 3

# scope: "all-layers"

default-catalogers: [ "go-module-file-cataloger", "go-module-binary-cataloger"]

format:
  json:
    pretty: true

golang:
  search-local-mod-cache-licenses: false
  search-remote-licenses: true
```

Invocation:
syft scan mongo:5.0.26-focal -o syft-json=/home/joerg/projects/mongo_inspect/mongo-syft-single.json -vv

Result 1:

Go Licenses are present in Syft-JSON

$HOME/go renamed to $HOME/go_
Same invocation.

Result 2:

Go licenses are not present in Syft-JSON

**Anything else we need to know?**:
N/A

**Environment**:
- Output of `syft version`:
Application: syft
Version:    1.2.0
BuildDate:  2024-04-12T18:31:58Z
GitCommit:  dde5d349b1eef740c285255e6a9e3a8f5c9938e1
GitDescription: v1.2.0
Platform:   linux/amd64
GoVersion:  go1.21.9
Compiler:   gc

- OS (e.g: `cat /etc/os-release` or similar):
uname -a
Linux delly 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

(Native Linux, no WSL)
