### ISSUE TITLE
Issue scanning Poetry Project with Syft 1.6 and cataloger=python-package-cataloger

### ISSUE THREAD

**Issue by mymichu** [anchore/syft#2954]
**What happened**:
We have updated Syft from Version 1.5.0 to 1.6.0 and discovered that it has issues scanning certain poetry.lock files. We try to scan a poetry project with the syft 1.6.0 with executing the following command:

```console
syft --output cyclonedx-json=reports/sbom-scan-licenses.cdx.json --source-name=blub scan .
````

and then we discovered that the output of the console has the following warning:

```console
[0001]  WARN cataloger failed cataloger=python-package-cataloger error=unable to parse poetry.lock: (0, 0): 
version = ">=1.0,<3"
markers = "platform_system == \"Windows\""
version = ">=1.6,<3"
]([]*toml.Tree) to trees location=/poetry.lock
```
and the json looks like followed:

```json
{
  "$schema": "http://cyclonedx.org/schema/bom-1.5.schema.json",
  "bomFormat": "CycloneDX",
  "specVersion": "1.5",
  "serialNumber": "urn:uuid:dac4442f-fb9e-4168-b204-567579c0314e",
  "version": 1,
  "metadata": {
    "timestamp": "2024-06-13T15:31:24+02:00",
    "tools": {
      "components": [
        {
          "type": "application",
          "author": "anchore",
          "name": "syft",
          "version": "1.6.0"
        }
      ]
    },
    "component": {
      "bom-ref": "af63bd4c8601b7f1",
      "type": "file",
      "name": "blub"
    }
  }
}
```

With Syft version 1.5.0, it was possible to scan the lock file without any issues. If we remove the following part (see below) from the lock file then Syft 1.6.0 works. We can not do that because other teams are maintaining the lock files. 

```toml
[package.dependencies]
msal = ">=0.4.1,<2.0.0"
packaging = "*"
portalocker = [
    {version = ">=1.0,<3", markers = "platform_system != \"Windows\""},
    {version = ">=1.6,<3", markers = "platform_system == \"Windows\""},
]
```

**What you expected to happen**:

I would expect that syft 1.6.0 has the same behaviour as the syft 1.5.0.

**Steps to reproduce the issue**:

Create poetry lock file and add the following snippet:

```toml
[package.dependencies]
msal = ">=0.4.1,<2.0.0"
packaging = "*"
portalocker = [
    {version = ">=1.0,<3", markers = "platform_system != \"Windows\""},
    {version = ">=1.6,<3", markers = "platform_system == \"Windows\""},
]
```
and execute  the following command within the poetry project:

```console
syft --output cyclonedx-json=reports/sbom-scan-licenses.cdx.json --source-name=blub scan .
```

**Anything else we need to know?**:

Currently nothing

**Environment**:
- Output of `syft version`: 1.6
- OS (e.g: `cat /etc/os-release` or similar): macOS 14.5
