### ISSUE TITLE
Adding "Stats" on the scan inside the json

### ISSUE THREAD

**Issue by TimBrown1611** [anchore/syft#3157]
**What would you like to be added**:
I had an idea to add "Stats" attribute to the schema, which will includes like "metadata" on the scan. for example: adding how much time each cataloger took.
I think this kind of information can make Syft tool better, since users could analyze better which tasks took longer, and tune it according to their needs (enable \ disable catalogers for example).
**Why is this needed**:
When running in debug mode things are going much slower, moreover it is much harder to work with logs instead of JSONs which you can analyze in much easier way without decreasing the performance.
**Additional context**:
it is related to this pr - https://github.com/anchore/syft/pull/3105

Do you think this kind of feature can be considered in the future? since it includes adding information to the final schema.

**Comment by wagoodman** [comment]
The SBOM is really attempting to capture what was found and how it was found. We attempt to keep auxiliary / secondary metadata out of the SBOM, especially if that data would make the SBOM more difficult to reproduce (such as timestamps). 

It sounds like from your use case you're interested in tracking along side the SBOM these performance metrics for future tuning of configuration -- is this true? If that's the case, we still want the configuration used to be captured in the SBOM (as it is today) but having the capability to configure syft to output structured logging would go  along way here. That way you'd need the SBOM and logs from a run to tune configuration for performance.

We're about 90% there code-wise. Here's what I mean:
- In go-logger (out logger interface), we have the logrus adapter already written and already has a [structured logging formatter](https://github.com/anchore/go-logger/blob/ee28a485904f6acd6a261a64925c9589128918dc/adapter/logrus/logger.go#L51) 
- we also use the `WithFields()` option on loggers all over the place, which tracks each `key=value` pair separately (which could support true structured logging)
- in clio (the application boilderplate/driver), we have a logger that can take a [custom formatter](https://github.com/anchore/clio/blob/4c50c054c5086bbe9c44a02cbe7d2e83e669e707/logging.go#L47C37-L47C67)
- in syft, we have a `log` configuration section

```yaml
log:
  # suppress all logging output (env: SYFT_LOG_QUIET)
  quiet: false

  # increase verbosity (-v = info, -vv = debug) (env: SYFT_LOG_VERBOSITY)
  verbosity: 0

  # explicitly set the logging level (available: [error warn info debug trace]) (env: SYFT_LOG_LEVEL)
  level: 'warn'

  # file path to write logs to (env: SYFT_LOG_FILE)
  file: ''
```

What's missing is the ability to specify structured logging from the config:
```
log:
   # output JSONL objects
   structured: true
```

or something like:
```
log:
   # in the future we could add support for more formats...
   format: jsonl
```

As well as the code change in clio to respond to that configuration.

@TimBrown1611 would this be a possible path forward for you?
