### ISSUE TITLE
Allow correction / overwrite of license information

### ISSUE THREAD

**Issue by markussiebert** [anchore/syft#3590]
**What would you like to be added**:

It would be beneficial to have a feature in Syft that allows users to override and correct license information for packages.
Looking at the configuration options, I couldn't find any option related to correcting license information.

**Why is this needed**:

In cases where no license or incorrect license information is found. I have observed this issue particularly with npm packages. Generally, this is due to package publishers not maintaining correct license information in their package.json files. However, a glance at the repository or the node_modules folder often reveals the correct license under which the package is published.

Of course it would be good to solve this at the source - in the repositories of the package maintainers, but it would only affect future package versions and might be outside the sphere of influence.

I found other inconsistency, were license information were wrong or misleading. So I think a solution to overwrite might a valid solution? 

What do you think?

**Additional context**:

I could imagine something like:

```yaml
licenseOverwrite:
- purl: pkg:npm/%40ogma/common@1.2.0     # Maybe allow things like 1.x >1.0.0<1.5.0
  data:
    value: "MIT",
    spdxExpression: "MIT",
    type: "declared",                                           # Maybe "userprovided"
    location:
      path: https://www.npmjs.com/package/@ogma/common?activeTab=code
```
