### ISSUE TITLE
Add Docker to Syft OCI Images

### ISSUE THREAD

**Issue by henrysachs** [anchore/syft#3603]
**What would you like to be added**:

Add Docker-CLI to the OCI Image 

**Why is this needed**:

To Perform a `syft image` in my Pipeline using the corresponding Image

**Additional context**:
I need to perform a `docker login` to allow syft to pull the image

**Comment by wagoodman** [comment]
Can you give an example of how you would use the docker cli and syft OCI image with this? I have a few different interpretations of the request and want to get some clarification.

I feel like there are a couple different ways to achieve this without adding docker to the image:

1. Use the `registry` scheme and specify credentials via syft configuration as environment variables. Note the `syft config ` shows a registry section:
```
registry:
  # skip TLS verification when communicating with the registry (env: SYFT_REGISTRY_INSECURE_SKIP_TLS_VERIFY)
  insecure-skip-tls-verify: false

  # use http instead of https when connecting to the registry (env: SYFT_REGISTRY_INSECURE_USE_HTTP)
  insecure-use-http: false

  # Authentication credentials for specific registries. Each entry describes authentication for a specific authority:
  # -   authority: the registry authority URL the URL to the registry (e.g. "docker.io", "localhost:5000", etc.) (env: SYFT_REGISTRY_AUTH_AUTHORITY)
  #     username: a username if using basic credentials (env: SYFT_REGISTRY_AUTH_USERNAME)
  #     password: a corresponding password (env: SYFT_REGISTRY_AUTH_PASSWORD)
  #     token: a token if using token-based authentication, mutually exclusive with username/password (env: SYFT_REGISTRY_AUTH_TOKEN)
  #     tls-cert: filepath to the client certificate used for TLS authentication to the registry (env: SYFT_REGISTRY_AUTH_TLS_CERT)
  #     tls-key: filepath to the client key used for TLS authentication to the registry (env: SYFT_REGISTRY_AUTH_TLS_KEY)
  auth: []

  # filepath to a CA certificate (or directory containing *.crt, *.cert, *.pem) used to generate the client certificate (env: SYFT_REGISTRY_CA_CERT)
  ca-cert: ''
```

in which case you can specify `-e SYFT_REGISTRY_AUTH_USERNAME=...` 
 and other vars in your `docker run` command


2. Share the host docker socket via a volume mount `-v /var/run/docker.sock:/var/run/docker.sock` and use the default `docker` scheme 

3. Share the ~/.docker credentials file via a volume similar to 2 (this might not work in some cases depending if a keychain is in use)
