### ISSUE TITLE
Syft is unable to extract license for bundled versions of google-http-client* libs

### ISSUE THREAD

**Issue by rafalsatl** [anchore/syft#3904]
**What happened**:
We have an artifact that bundles some libraries including a few google-http-client ones: https://maven.artifacts.atlassian.com/com/atlassian/oauth2/oauth2-client-plugin/4.2.6/

**What you expected to happen**:
An sbom gets generated and contains license information for all the artefacts found by syft (see also META-INF/maven/... )

**Steps to reproduce the issue**:
```
wget https://maven.artifacts.atlassian.com/com/atlassian/oauth2/oauth2-client-plugin/4.2.6/oauth2-client-plugin-4.2.6.jar
syft . -o cyclonedx-json > test.json
```

The sbom node for "google-http-client-gson" does not have license information.

**Anything else we need to know?**:

The license information for these libraries is propagated/managed in the parent pom:
https://repo1.maven.org/maven2/com/google/http-client/google-http-client-gson/1.47.0/google-http-client-gson-1.47.0.pom
https://repo1.maven.org/maven2/com/google/http-client/google-http-client-parent/1.47.0/google-http-client-parent-1.47.0.pom

**Environment**:
- Output of `syft version`:
- ➜  syft-issue syft version                                                                                                                 [16/05/25 | 08:54:37]
Application: syft
Version:    1.24.0
BuildDate:  2025-05-14T13:12:05Z
GitCommit:  Homebrew
GitDescription: [not provided]
Platform:   darwin/arm64
GoVersion:  go1.24.3
Compiler:   gc

- OS (e.g: `cat /etc/os-release` or similar):
macOs 15.4.1

**Comment by VictorHuu** [comment]
Hello @rafalsatl ,don't worry,this is the expected behavior. It's due to the default close-down of the config option 'use-network'.

The relative path here can be only applied when it comes to the source code of a java project, not in a java archive. So we must retrive the remote URL to get the pom.

And here's the configuration ```.config.yaml``` you can create:
``` yaml
java:
   maven-url: "https://repo1.maven.org/maven2"
   max-parent-recursive-depth: 5
   # enables Syft to use the network to fill in more detailed information about artifacts
   # currently this enables searching maven-url for license data
   # when running across pom.xml files that could have more information, syft will
   # explicitly search maven for license information by querying the online pom when this is true
   # this option is helpful for when the parent pom has more data,
   # that is not accessible from within the final built artifact
   use-network: true
```
Then 
``` bash
syft -c .config.yaml oauth2-client-plugin-4.2.6.jar -o cyclonedx-json > test.json
```
works!
