### ISSUE TITLE
Support XXH and other performant hash algorithms

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#3966]
Today we support hashing sources as well as files within sources, which is all configurable:

```yaml
# .syft.yaml

file:
  metadata:
    # the file digest algorithms to use when cataloging files (options: "md5", "sha1", "sha224", "sha256", "sha384", "sha512") (env: SYFT_FILE_METADATA_DIGESTS)
    digests:
      - 'sha1'
      - 'sha256'

source:
  file:
    # the file digest algorithms to use on the scanned file (options: "md5", "sha1", "sha224", "sha256", "sha384", "sha512") (env: SYFT_SOURCE_FILE_DIGESTS)
    digests:
      - 'SHA-256'
```

We should add more performant algorithms such as XXH64 (insert more here, open to suggestions!).
