### ISSUE TITLE
support external registry configuration

### ISSUE THREAD

**Issue by kzantow** [anchore/syft#502]
**What would you like to be added**:
Related to the [anchore/sbom-action, support for external registry connections](https://github.com/anchore/sbom-action/issues/29): it may be tedious if a user needs to configure registry connections multiple times. It would be ideal if a `docker login` command or other external registry configuration could be used to achieve this without having to configure it for each invocation of Syft.

**Why is this needed**:
Make the user experience nicer in some use cases.

**Additional context**:

**Comment by spiffcs** [comment]
Just commenting on this as I'm going through it:
```
it may be tedious if a user needs to configure registry connections multiple times. 
It would be ideal if a docker login command or other external registry configuration 
could be used to achieve this without having to configure it for each invocation of Syft.
```

Syft already sources credentials correctly if a user has previously run `docker login`.

The purpose of this issue is to bring advanced features to syft regarding credential discovery even if something like the docker daemon is not installed.

**Comment by luhring** [comment]
>Syft already sources credentials correctly if a user has previously run docker login.

Interesting... just so I understand correctly, this statement is true even when Docker is not running or the `registry:` scheme is used?

**Comment by spiffcs** [comment]
No we still need the docker daemon for that - that's what I'm trying to have setup to answer this issue

**Comment by luhring** [comment]
I gotcha, okay great. 👍

**Comment by spiffcs** [comment]
After more research and configuration I've been able to get `syft` working on my local k3d using the current authentication options that are available OUTSIDE of the `syft` `config.yaml`

This comment will detail the options/process for getting syft running on a cluster where the docker daemon is not present, a config file with secrets is impractical, and where authorization to private registries can only be done as detailed [in the authn library here](https://github.com/google/go-containerregistry/tree/main/pkg/authn).

Note: while this comment uses kubernetes secrets in their basic out-of-the-box implementation, the author assumes your production clusters are using best practices surrounding secret storage, access, and management:
- [Vault](https://www.youtube.com/watch?v=FhUJYwM_xy0)
- [Securing Kubernetes Secrets](https://www.youtube.com/watch?v=DNKcRUyz4Hw)
- [Turtles all the way down](https://www.youtube.com/watch?v=rLHJZE2XKl8)

You'll need access to a development cluster to follow along.

If you're running on osx I can suggest [k3d](https://github.com/rancher/k3d).  [k3s](https://rancher.com/docs/k3s/latest/en/quick-start/) is also an awesome way to get started on Kubernetes.

1. Create a secret. The value of `config.json` is important and it refers to the specification outlined [here](https://github.com/google/go-containerregistry/tree/main/pkg/authn#the-config-file).

An example plain text `config.json` looks something like this:
```
// config.json

{
	"auths": {
		"registry.example.com": {
			"username": "AzureDiamond",
			"password": "hunter2"
		}
	}
}
```

While this comment doesn't cover this scope, there is a place where a k8s controller could generate a secret with a token on expiration of the previous token. For authn token configuration the `config.json` looks something like this:
```
// config_token.json

{
	"auths": {
		"registry.example.com": {
			"auth": "QXp1cmVEaWFtb25kOmh1bnRlcjI="
		}
	}
}
```

Here is the `secret.yaml` file that the pod configuration will consume as a volume.
```
# secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: registry-config
  namespace: syft
data:
  config.json: <base64 encoded config.json>
```

`kubectl apply -f secret.yaml`

2. Create your pod running syft. The env `DOCKER_CONFIG` is important because it advertises to the `authn` library where to look for the credential file. In the below example, setting `DOCKER_CONFIG=/config` informs the library that credentials can be found at `/config/config.json`. This is why we used `config.json` as the key for our secret. When mounted into containers the secrets' key is used as the filename.

The `voluemMounts` section mounts our secret to `/config`. The `volumes` section names our volume and sources the secret we created in step one as the file we will be mounting.
```
# pod.yaml

apiVersion: v1
kind: Pod
spec:
  containers:
    - image: anchore/syft:latest
      name: syft-private-registry-demo
      env:
        - name: DOCKER_CONFIG
          value: /config
      volumeMounts:
      - mountPath: /config
        name: registry-config
        readOnly: true
      args:
        - <private_image>
  volumes:
  - name: registry-config
    secret:
      secretName: registry-config
```

Using the above information - users should be able to configure private registry access without having to interface or shim into the `grype` or `syft` configuration files OR be dependent on a docker daemon, (or some other runtime software) for registry configuration and access.
