### ISSUE TITLE
Missing the metadata field for Kubernetes pod usage

### ISSUE THREAD

**Issue by majinghe** [anchore/syft#787]
**What happened**:

When try to use syft on Kubernetes, according to the docs on README,  **Docker Credentials in Kubernetes** part,  the pod yaml file is as below on docs

```
apiVersion: v1
kind: Pod
spec:
  containers:
    - image: anchore/syft:latest
      name: syft-private-registry-demo
      env:
        - name: DOCKER_CONFIG
          value: /config
      volumeMounts:
      - mountPath: /config
        name: registry-config
        readOnly: true
      args:
        - <private_image>
  volumes:
  - name: registry-config
    secret:
      secretName: registry-config
```
But i think the `metadata` field is missing. If try to install using the above yaml file, the error will be as below

```
error: error when retrieving current configuration of:
Resource: "/v1, Resource=pods", GroupVersionKind: "/v1, Kind=Pod"
Name: "", Namespace: "test"
from server for: "pod.yaml": resource name may not be empty
```

But if add the `metadata` field, it will works fine.
